// ============================================
// BASE DE DADOS DE PRODUTOS (FONTE ÚNICA)
// ============================================
// Ordem estratégica: mistura itens com maior potencial de venda
// (seleções + clubes grandes populares) com itens em estoque
// Cada produto tem detalhes completos para exibição

const SIZE_ORDER = ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'];

const PRODUTOS_DB = [
  // ⭐ BRASIL + ARGENTINA - mais vendidos
  {
    id: 1,
    nome: 'Camisa do Brasil I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: '🔥 Mais vendido',
    imagem: 'img/brasil-1-2627-1.jpg',
    imagens: ['img/brasil-1-2627-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Brasil',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Amarelo',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 16,
    nome: 'Camisa do Brasil II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/brasil-2-2627.jpg',
    imagens: ['img/brasil-2-2627.jpg', 'img/brasil-2-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Brasil',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 8,
    nome: 'Camisa da Argentina I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/argentina-1-2627-1.jpg',
    imagens: ['img/argentina-1-2627-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Argentina',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul e branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ CORINTHIANS + SANTOS - clubes nacionais populares
  {
    id: 23,
    nome: 'Camisa do Santos I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/santos-1-2627.jpg',
    imagens: ['img/santos-1-2627.jpg', 'img/santos-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Umbro',
    clube: 'Santos',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 23,
    nome: 'Camisa do Santos III 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/santos-3-2526.jpg',
    imagens: ['img/santos-3-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Umbro',
    clube: 'Santos',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 18,
    nome: 'Camisa do Corinthians I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/corinthians-1-2627.jpg',
    imagens: ['img/corinthians-1-2627.jpg', 'img/corinthians-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 0, G: 0, GG: 0, G1: 10, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Corinthians',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Preto',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 19,
    nome: 'Camisa do Corinthians II 26/27 (laranja)',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/corinthians-2-2627.jpg',
    imagens: ['img/corinthians-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 10, G3: 0 },
    marca: 'Nike',
    clube: 'Corinthians',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Laranja',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 59,
    nome: 'Camisa do Corinthians III 25/26',
    preco: 139.9,
    descricao: 'Terceira camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/corinthians-3-2526.jpg',
    imagens: ['img/corinthians-3-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Corinthians',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto e rosa',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  // ⭐ REAL MADRID (sob encomenda mas muito popular)
  {
    id: 3,
    nome: 'Camisa do Real Madrid I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: '🔥 Mais vendido',
    imagem: 'img/real-madrid-1-2627.jpg',
    imagens: ['img/real-madrid-1-2627.jpg', 'img/real-madrid-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Real Madrid',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ BARCELONA 26/27 + Barcelona III 25/26
  {
    id: 20,
    nome: 'Camisa do Barcelona I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/barcelona-1-2627.jpg',
    imagens: ['img/barcelona-1-2627.jpg', 'img/barcelona-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 10, G3: 10 },
    marca: 'Nike',
    clube: 'Barcelona',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul e grená',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 26,
    nome: 'Camisa do Barcelona III 25/26',
    preco: 139.9,
    descricao: 'Terceira camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/barcelona-2-2526-1.jpg',
    imagens: ['img/barcelona-2-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 10, G2: 10, G3: 0 },
    marca: 'Nike',
    clube: 'Barcelona',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Laranja',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ FRANÇA + INGLATERRA
  {
    id: 11,
    nome: 'Camisa da França I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/franca-1-2627.jpg',
    imagens: ['img/franca-1-2627.jpg', 'img/franca-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P:0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'França',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 10,
    nome: 'Camisa da Inglaterra I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/inglaterra-1-2627.jpg',
    imagens: ['img/inglaterra-1-2627.jpg', 'img/inglaterra-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Inglaterra',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ PORTUGAL + HOLANDA
  {
    id: 6,
    nome: 'Camisa de Portugal I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/portugal-1-2627.jpg',
    imagens: ['img/portugal-1-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Portugal',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Vermelho e verde',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 14,
    nome: 'Camisa da Holanda I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/holanda-1-2627.jpg',
    imagens: ['img/holanda-1-2627.jpg', 'img/holanda-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Holanda',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Laranja',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ PSG + CHELSEA
  {
    id: 22,
    nome: 'Camisa do PSG I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/psg-1-2627.jpg',
    imagens: ['img/psg-1-2627.jpg', 'img/psg-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'PSG',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 31,
    nome: 'Camisa do Chelsea I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/chelsea-1-2526-1.jpg',
    imagens: ['img/chelsea-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 10, G3: 0 },
    marca: 'Nike',
    clube: 'Chelsea',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ATLÉTICO MINEIRO + BOTAFOGO
  {
    id: 24,
    nome: 'Camisa do Atlético Mineiro I 24/25',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/atletico-mineiro-1-2526.jpg',
    imagens: ['img/atletico-mineiro-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 10, G: 10, GG: 10, G1: 10, G2: 10, G3: 0 },
    marca: 'Adidas',
    clube: 'Atlético Mineiro',
    tipo: 'Torcedor',
    temporada: '24/25',
    material: 'Poliéster leve',
    cor: 'Preto e branco',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 30,
    nome: 'Camisa do Botafogo I 24/25',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 24/25',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/botafogo-1-2526-1.jpg',
    imagens: ['img/botafogo-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 10, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Reebok',
    clube: 'Botafogo',
    tipo: 'Torcedor',
    temporada: '24/25',
    material: 'Poliéster leve',
    cor: 'Preto e branco',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  // ESPANHA + ITÁLIA
  {
    id: 4,
    nome: 'Camisa da Espanha I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/espanha-1-2627.jpg',
    imagens: ['img/espanha-1-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Espanha',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Vermelho',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 15,
    nome: 'Camisa da Itália I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/italia-1-2627.jpg',
    imagens: ['img/italia-1-2627.jpg', 'img/italia-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Puma',
    clube: 'Itália',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // BORUSSIA + BAYERN
  {
    id: 29,
    nome: 'Camisa do Borussia Dortmund I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/borussia-dortmund-1-2526-1.jpg',
    imagens: ['img/borussia-dortmund-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 10, G3: 0 },
    marca: 'Puma',
    clube: 'Borussia Dortmund',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto e amarelo',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 27,
    nome: 'Camisa do Bayern de Munique II 25/26',
    preco: 139.9,
    descricao: 'Segunda camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/bayern-de-munique-2-2526-1.jpg',
    imagens: ['img/bayern-de-munique-2-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 0, G: 10, GG: 10, G1: 10, G2: 10, G3: 0 },
    marca: 'Adidas',
    clube: 'Bayern de Munique',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // COLÔMBIA + EUA
  {
    id: 13,
    nome: 'Camisa da Colômbia I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/colombia-1-2627.jpg',
    imagens: ['img/colombia-1-2627.jpg', 'img/colombia-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Colômbia',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Amarelo',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 17,
    nome: 'Camisa dos Estados Unidos I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/estados-unidos-1-2627.jpg',
    imagens: ['img/estados-unidos-1-2627.jpg', 'img/estados-unidos-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Estados Unidos',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco e azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ARSENAL + ATLÉTICO DE MADRID
  {
    id: 32,
    nome: 'Camisa do Arsenal I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/arsenal-1-2526-1.jpg',
    imagens: ['img/arsenal-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 0, G: 0, GG: 10, G1: 10, G2: 10, G3: 0 },
    marca: 'Adidas',
    clube: 'Arsenal',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Vermelho e branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 33,
    nome: 'Camisa do Atlético de Madrid II 25/26',
    preco: 139.9,
    descricao: 'Segunda camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/atlético-de-madrid-2-2526-1.jpg',
    imagens: ['img/atlético-de-madrid-2-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Atlético de Madrid',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Azul e amarelo',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // CORINTHIANS II + BENFICA
  {
    id: 28,
    nome: 'Camisa do Benfica I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/benfica-1-2526-1.jpg',
    imagens: ['img/benfica-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Benfica',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Vermelho e branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ SOB ENCOMENDA
  {
    id: 7,
    nome: 'Camisa de Portugal II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/portugal-2-2627.jpg',
    imagens: ['img/portugal-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Portugal',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 9,
    nome: 'Camisa da Argentina II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/argentina-2-2627.jpg',
    imagens: ['img/argentina-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Argentina',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 5,
    nome: 'Camisa da Espanha II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/espanha-2-2627.jpg',
    imagens: ['img/espanha-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Espanha',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 12,
    nome: 'Camisa da França II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/franca-2-2627.jpg',
    imagens: ['img/franca-2-2627.jpg', 'img/franca-2-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'França',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco e azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ NOVAS CAMISAS
  {
    id: 34,
    nome: 'Camisa do West Ham United I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/west-ham-1-2526.jpg',
    imagens: ['img/west-ham-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Umbro',
    clube: 'West Ham United',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Claret e azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 35,
    nome: 'Camisa do Tottenham III 25/26',
    preco: 139.9,
    descricao: 'Terceira camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/tottenham-3-2526.jpg',
    imagens: ['img/tottenham-3-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 10, G: 10, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Tottenham',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto e azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 36,
    nome: 'Camisa do Sporting I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/sporting-1-2526.jpg',
    imagens: ['img/sporting-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 10, G1: 0, G2: 0, G3: 0 },
    marca: 'Puma',
    clube: 'Sporting',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Verde e branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 37,
    nome: 'Camisa do São Paulo III 25',
    preco: 139.9,
    descricao: 'Terceira camisa - temporada 2025',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/sao-paulo-3-25.jpg',
    imagens: ['img/sao-paulo-3-25.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'New Balance',
    clube: 'São Paulo',
    tipo: 'Torcedor',
    temporada: '2025',
    material: 'Poliéster leve',
    cor: 'Cinza',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 38,
    nome: 'Camisa do São Paulo I 25',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/sao-paulo-1-25.jpg',
    imagens: ['img/sao-paulo-1-25.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'New Balance',
    clube: 'São Paulo',
    tipo: 'Torcedor',
    temporada: '2025',
    material: 'Poliéster leve',
    cor: 'Branco e vermelho',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 39,
    nome: 'Camisa do Tottenham II 25/26',
    preco: 139.9,
    descricao: 'Segunda camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/tottenham-2-2526.jpg',
    imagens: ['img/tottenham-2-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 0, G1: 10, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Tottenham',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Azul marinho',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 40,
    nome: 'Camisa do Real Madrid I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/real-madrid-1-2526.jpg',
    imagens: ['img/real-madrid-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 10, G1: 10, G2: 10, G3: 0 },
    marca: 'Adidas',
    clube: 'Real Madrid',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 41,
    nome: 'Camisa da Roma I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/roma-1-2526.jpg',
    imagens: ['img/roma-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Roma',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Vinho',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 42,
    nome: 'Camisa do Palmeiras III 25',
    preco: 139.9,
    descricao: 'Terceira camisa - temporada 2025',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/palmeiras-3-25.jpg',
    imagens: ['img/palmeiras-3-25.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 10, G: 10, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Puma',
    clube: 'Palmeiras',
    tipo: 'Torcedor',
    temporada: '2025',
    material: 'Poliéster leve',
    cor: 'Amarelo e verde',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 43,
    nome: 'Camisa do Real Madrid II 25/26',
    preco: 139.9,
    descricao: 'Segunda camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/real-madrid-2-2526.jpg',
    imagens: ['img/real-madrid-2-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 10, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Real Madrid',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ NOVAS CAMISAS (2º lote)
  {
    id: 44,
    nome: 'Camisa do Newcastle I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/newcastle-1-2526.jpg',
    imagens: ['img/newcastle-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 10 },
    marca: 'Adidas',
    clube: 'Newcastle',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto e branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 45,
    nome: 'Camisa do Olympique de Marseille I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/olympique-marseille-1-2526.jpg',
    imagens: ['img/olympique-marseille-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 10, G1: 0, G2: 0, G3: 0 },
    marca: 'Puma',
    clube: 'Olympique de Marseille',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Azul claro',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 46,
    nome: 'Camisa do Manchester City I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/manchester-city-1-2526.jpg',
    imagens: ['img/manchester-city-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 10, G: 10, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Puma',
    clube: 'Manchester City',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Azul celeste',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 47,
    nome: 'Camisa do Manchester United I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/manchester-united-1-2526.jpg',
    imagens: ['img/manchester-united-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Manchester United',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Vermelho',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 48,
    nome: 'Camisa do Internacional I 25',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/internacional-1-25.jpg',
    imagens: ['img/internacional-1-25.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 10, G: 10, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Internacional',
    tipo: 'Torcedor',
    temporada: '2025',
    material: 'Poliéster leve',
    cor: 'Vermelho',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 49,
    nome: 'Camisa da Inter de Milão II 25/26',
    preco: 139.9,
    descricao: 'Segunda camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/inter-milao-2-2526.jpg',
    imagens: ['img/inter-milao-2-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 10, G3: 0 },
    marca: 'Nike',
    clube: 'Inter de Milão',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 50,
    nome: 'Camisa da Inter de Milão I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/inter-milao-1-2526.jpg',
    imagens: ['img/inter-milao-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Inter de Milão',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto e azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 51,
    nome: 'Camisa do Internacional II 25',
    preco: 139.9,
    descricao: 'Segunda camisa - temporada 2025',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/internacional-2-25.jpg',
    imagens: ['img/internacional-2-25.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 0, GG: 10, G1: 10, G2: 10, G3: 0 },
    marca: 'Adidas',
    clube: 'Internacional',
    tipo: 'Torcedor',
    temporada: '2025',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 52,
    nome: 'Camisa do Fluminense I 25',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/fluminense-1-25.jpg',
    imagens: ['img/fluminense-1-25.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 0, G: 10, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Umbro',
    clube: 'Fluminense',
    tipo: 'Torcedor',
    temporada: '2025',
    material: 'Poliéster leve',
    cor: 'Verde, vermelho e branco',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 53,
    nome: 'Camisa da Inter de Milão III 25/26',
    preco: 139.9,
    descricao: 'Terceira camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/inter-milao-3-2526.jpg',
    imagens: ['img/inter-milao-3-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 10, G: 10, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Inter de Milão',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ NOVAS CAMISAS (3º lote)
  {
    id: 54,
    nome: 'Camisa do Flamengo Treino I 26/27',
    preco: 139.9,
    descricao: 'Segunda camisa - temporada 26/27',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/flamengo-treino-1-2627.jpg',
    imagens: ['img/flamengo-treino-1-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Flamengo',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Bege',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 58,
    nome: 'Camisa do Flamengo Treino II 26/27',
    preco: 139.9,
    descricao: 'Segunda camisa de treino - temporada 26/27',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/flamengo-treino-2-2627.jpg',
    imagens: ['img/flamengo-treino-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Flamengo',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Marrom',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 55,
    nome: 'Camisa da Fiorentina I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/fiorentina-1-2526.jpg',
    imagens: ['img/fiorentina-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 10, G2: 10, G3: 0 },
    marca: 'Kappa',
    clube: 'Fiorentina',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Roxo',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 56,
    nome: 'Camisa do Cruzeiro III 26/27',
    preco: 139.9,
    descricao: 'Terceira camisa - temporada 26/27',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/cruzeiro-3-2627.jpg',
    imagens: ['img/cruzeiro-3-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 10, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Cruzeiro',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco e azul',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 57,
    nome: 'Camisa do Cruzeiro Treino II 26/27',
    preco: 139.9,
    descricao: 'Versão de treino com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/cruzeiro-treino-2-2627.jpg',
    imagens: ['img/cruzeiro-treino-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Cruzeiro',
    tipo: 'Treino',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 60,
    nome: 'Camisa da Coreia I 25/26',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/coreia-1-2526.jpg',
    imagens: ['img/coreia-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Coreia do Sul',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Vermelho',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 61,
    nome: 'Camisa do Colo-Colo Centenario II 2025',
    preco: 139.9,
    descricao: 'Comemoração dos 100 anos - versão goleiro',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/colo-colo-centenario-2-2025.jpg',
    imagens: ['img/colo-colo-centenario-2-2025.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 10, G: 0, GG: 0, G1: 10, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Colo-Colo',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 62,
    nome: 'Camisa do Botafogo V 25/26',
    preco: 139.9,
    descricao: 'Quinta camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/botafogo-5-2526.jpg',
    imagens: ['img/botafogo-5-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 10, G: 10, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Reebok',
    clube: 'Botafogo',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto e cinza',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  // ⭐ RETRO
  {
    id: 63,
    nome: 'Camisa do Brasil Retro I 1998',
    preco: 149.9,
    descricao: 'Versão retrô - edição 1998',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/brasil-retro-1-1998.jpg',
    imagens: ['img/brasil-retro-1-1998.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 0, G: 0, GG: 10, G1: 10, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Brasil',
    tipo: 'Retrô',
    temporada: '1998',
    material: 'Poliéster leve',
    cor: 'Amarelo',
    escudo: 'Bordado',
    origem: 'Importado'
  }
];