// ============================================
// BASE DE DADOS DE PRODUTOS (FONTE ÚNICA)
// ============================================
// Ordem estratégica: mistura itens com maior potencial de venda
// (seleções + clubes grandes populares) com itens em estoque
// Cada produto tem detalhes completos para exibição

const SIZE_ORDER = ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'];

const PRODUTOS_DB = [
  // ⭐ BRASIL + ARGENTINA - mais vendidos
  {
    id: 1,
    nome: 'Camisa do Brasil I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: '🔥 Mais vendido',
    imagem: 'img/brasil-1-2627-1.jpg',
    imagens: ['img/brasil-1-2627-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 15, M: 20, G: 18, GG: 14, G1: 10, G2: 8, G3: 5 },
    marca: 'Nike',
    clube: 'Brasil',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Amarelo',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 8,
    nome: 'Camisa da Argentina I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/argentina-1-2627-1.jpg',
    imagens: ['img/argentina-1-2627-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 12, M: 14, G: 12, GG: 10, G1: 7, G2: 5, G3: 3 },
    marca: 'Adidas',
    clube: 'Argentina',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul e branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ CORINTHIANS + SANTOS - clubes nacionais populares
  {
    id: 18,
    nome: 'Camisa do Corinthians I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/corinthians-1-2627.jpg',
    imagens: ['img/corinthians-1-2627.jpg', 'img/corinthians-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 8, M: 10, G: 9, GG: 7, G1: 5, G2: 3, G3: 2 },
    marca: 'Nike',
    clube: 'Corinthians',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Preto',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 23,
    nome: 'Camisa do Santos I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/santos-1-2627.jpg',
    imagens: ['img/santos-1-2627.jpg', 'img/santos-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 6, M: 8, G: 7, GG: 5, G1: 4, G2: 2, G3: 1 },
    marca: 'Umbro',
    clube: 'Santos',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  // ⭐ REAL MADRID (sob encomenda mas muito popular)
  {
    id: 3,
    nome: 'Camisa do Real Madrid I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: '🔥 Mais vendido',
    imagem: 'img/real-madrid-1-2627.jpg',
    imagens: ['img/real-madrid-1-2627.jpg', 'img/real-madrid-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Real Madrid',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ BARCELONA 26/27 + Barcelona III 25/26
  {
    id: 20,
    nome: 'Camisa do Barcelona I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/barcelona-1-2627.jpg',
    imagens: ['img/barcelona-1-2627.jpg', 'img/barcelona-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 12, G: 10, GG: 8, G1: 6, G2: 4, G3: 2 },
    marca: 'Nike',
    clube: 'Barcelona',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul e grená',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 26,
    nome: 'Camisa do Barcelona III 25/26',
    preco: 139.9,
    descricao: 'Terceira camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/barcelona-2-2526-1.jpg',
    imagens: ['img/barcelona-2-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 5, M: 6, G: 7, GG: 5, G1: 10, G2: 10, G3: 3 },
    marca: 'Nike',
    clube: 'Barcelona',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Laranja',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ FRANÇA + INGLATERRA
  {
    id: 11,
    nome: 'Camisa da França I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/franca-1-2627.jpg',
    imagens: ['img/franca-1-2627.jpg', 'img/franca-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 12, M: 14, G: 13, GG: 10, G1: 8, G2: 5, G3: 3 },
    marca: 'Nike',
    clube: 'França',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 10,
    nome: 'Camisa da Inglaterra I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/inglaterra-1-2627.jpg',
    imagens: ['img/inglaterra-1-2627.jpg', 'img/inglaterra-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 12, G: 10, GG: 8, G1: 6, G2: 4, G3: 2 },
    marca: 'Nike',
    clube: 'Inglaterra',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ PORTUGAL + HOLANDA
  {
    id: 6,
    nome: 'Camisa de Portugal I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/portugal-1-2627.jpg',
    imagens: ['img/portugal-1-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 12, G: 11, GG: 8, G1: 6, G2: 4, G3: 2 },
    marca: 'Nike',
    clube: 'Portugal',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Vermelho e verde',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 14,
    nome: 'Camisa da Holanda I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/holanda-1-2627.jpg',
    imagens: ['img/holanda-1-2627.jpg', 'img/holanda-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 9, M: 11, G: 10, GG: 8, G1: 5, G2: 3, G3: 2 },
    marca: 'Nike',
    clube: 'Holanda',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Laranja',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ PSG + CHELSEA
  {
    id: 22,
    nome: 'Camisa do PSG I 26/27',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/psg-1-2627.jpg',
    imagens: ['img/psg-1-2627.jpg', 'img/psg-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 9, M: 10, G: 8, GG: 7, G1: 5, G2: 3, G3: 2 },
    marca: 'Nike',
    clube: 'PSG',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 31,
    nome: 'Camisa do Chelsea I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/chelsea-1-2526-1.jpg',
    imagens: ['img/chelsea-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 12, M: 12, G: 11, GG: 10, G1: 10, G2: 10, G3: 5 },
    marca: 'Nike',
    clube: 'Chelsea',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ATLÉTICO MINEIRO + BOTAFOGO
  {
    id: 24,
    nome: 'Camisa do Atlético Mineiro I 24/25',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/atletico-mineiro-1-2526.jpg',
    imagens: ['img/atletico-mineiro-1-2526.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 8, M: 11, G: 11, GG: 10, G1: 10, G2: 10, G3: 5 },
    marca: 'Adidas',
    clube: 'Atlético Mineiro',
    tipo: 'Torcedor',
    temporada: '24/25',
    material: 'Poliéster leve',
    cor: 'Preto e branco',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 30,
    nome: 'Camisa do Botafogo I 24/25',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 24/25',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/botafogo-1-2526-1.jpg',
    imagens: ['img/botafogo-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 5, M: 12, G: 8, GG: 6, G1: 3, G2: 2, G3: 1 },
    marca: 'Reebok',
    clube: 'Botafogo',
    tipo: 'Torcedor',
    temporada: '24/25',
    material: 'Poliéster leve',
    cor: 'Preto e branco',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  // ESPANHA + ITÁLIA
  {
    id: 4,
    nome: 'Camisa da Espanha I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/espanha-1-2627.jpg',
    imagens: ['img/espanha-1-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 10, M: 12, G: 11, GG: 9, G1: 6, G2: 4, G3: 2 },
    marca: 'Adidas',
    clube: 'Espanha',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Vermelho',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 15,
    nome: 'Camisa da Itália I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/italia-1-2627.jpg',
    imagens: ['img/italia-1-2627.jpg', 'img/italia-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 8, M: 10, G: 9, GG: 7, G1: 5, G2: 3, G3: 2 },
    marca: 'Puma',
    clube: 'Itália',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // BORUSSIA + BAYERN
  {
    id: 29,
    nome: 'Camisa do Borussia Dortmund I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/borussia-dortmund-1-2526-1.jpg',
    imagens: ['img/borussia-dortmund-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 12, M: 11, G: 12, GG: 10, G1: 10, G2: 10, G3: 5 },
    marca: 'Puma',
    clube: 'Borussia Dortmund',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto e amarelo',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 27,
    nome: 'Camisa do Bayern de Munique II 25/26',
    preco: 139.9,
    descricao: 'Segunda camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/bayern-de-munique-2-2526-1.jpg',
    imagens: ['img/bayern-de-munique-2-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 12, M: 8, G: 11, GG: 10, G1: 10, G2: 10, G3: 4 },
    marca: 'Adidas',
    clube: 'Bayern de Munique',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Preto',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // COLÔMBIA + EUA
  {
    id: 13,
    nome: 'Camisa da Colômbia I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/colombia-1-2627.jpg',
    imagens: ['img/colombia-1-2627.jpg', 'img/colombia-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 8, M: 10, G: 9, GG: 7, G1: 5, G2: 3, G3: 2 },
    marca: 'Adidas',
    clube: 'Colômbia',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Amarelo',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 17,
    nome: 'Camisa dos Estados Unidos I 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/estados-unidos-1-2627.jpg',
    imagens: ['img/estados-unidos-1-2627.jpg', 'img/estados-unidos-1-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 7, M: 9, G: 8, GG: 6, G1: 4, G2: 3, G3: 1 },
    marca: 'Nike',
    clube: 'Estados Unidos',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco e azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ARSENAL + ATLÉTICO DE MADRID
  {
    id: 32,
    nome: 'Camisa do Arsenal I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/arsenal-1-2526-1.jpg',
    imagens: ['img/arsenal-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 12, M: 8, G: 9, GG: 11, G1: 10, G2: 10, G3: 4 },
    marca: 'Adidas',
    clube: 'Arsenal',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Vermelho e branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 33,
    nome: 'Camisa do Atlético de Madrid II 25/26',
    preco: 139.9,
    descricao: 'Segunda camisa - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/atlético-de-madrid-2-2526-1.jpg',
    imagens: ['img/atlético-de-madrid-2-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 11, M: 12, G: 11, GG: 10, G1: 10, G2: 5, G3: 3 },
    marca: 'Nike',
    clube: 'Atlético de Madrid',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Azul e branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // CORINTHIANS II + BENFICA
  {
    id: 19,
    nome: 'Camisa do Corinthians II 26/27 (laranja)',
    preco: 139.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/corinthians-2-2627.jpg',
    imagens: ['img/corinthians-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 4, M: 6, G: 5, GG: 4, G1: 3, G2: 2, G3: 1 },
    marca: 'Nike',
    clube: 'Corinthians',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Laranja',
    escudo: 'Bordado',
    origem: 'Nacional'
  },
  {
    id: 28,
    nome: 'Camisa do Benfica I 25/26',
    preco: 139.9,
    descricao: 'Versão torcedor - temporada 25/26',
    prazo: 'Entrega imediata',
    destaque: 'Em estoque',
    imagem: 'img/benfica-1-2526-1.jpg',
    imagens: ['img/benfica-1-2526-1.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 5, M: 6, G: 7, GG: 11, G1: 10, G2: 4, G3: 2 },
    marca: 'Adidas',
    clube: 'Benfica',
    tipo: 'Torcedor',
    temporada: '25/26',
    material: 'Poliéster leve',
    cor: 'Vermelho e branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  // ⭐ SOB ENCOMENDA
  {
    id: 16,
    nome: 'Camisa do Brasil II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/brasil-2-2627.jpg',
    imagens: ['img/brasil-2-2627.jpg', 'img/brasil-2-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Brasil',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 7,
    nome: 'Camisa de Portugal II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/portugal-2-2627.jpg',
    imagens: ['img/portugal-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'Portugal',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 9,
    nome: 'Camisa da Argentina II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/argentina-2-2627.jpg',
    imagens: ['img/argentina-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Argentina',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 5,
    nome: 'Camisa da Espanha II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/espanha-2-2627.jpg',
    imagens: ['img/espanha-2-2627.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Adidas',
    clube: 'Espanha',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Azul',
    escudo: 'Bordado',
    origem: 'Importado'
  },
  {
    id: 12,
    nome: 'Camisa da França II 26/27',
    preco: 149.9,
    descricao: 'Versão torcedor com tecido leve e respirável',
    prazo: 'Sob encomenda',
    destaque: 'Sob encomenda',
    imagem: 'img/franca-2-2627.jpg',
    imagens: ['img/franca-2-2627.jpg', 'img/franca-2-2627-2.jpg'],
    tamanhos: ['P', 'M', 'G', 'GG', 'G1', 'G2', 'G3'],
    estoque: { P: 0, M: 0, G: 0, GG: 0, G1: 0, G2: 0, G3: 0 },
    marca: 'Nike',
    clube: 'França',
    tipo: 'Torcedor',
    temporada: '26/27',
    material: 'Poliéster leve',
    cor: 'Branco e azul',
    escudo: 'Bordado',
    origem: 'Importado'
  }
];